Adding SepaDD Associations
form3tech-oss/terraform-provider-form3 pull request #107
Opened 2020-09-16 13:48 UTC by AMCR

Adding SepaDD associations

2020-09-16 14:21 UTC, jacoelho-form3 approved these changes
LGTM

2020-09-16 14:23 UTC, rossmcf requested changes
This looks good to me. One thought: do we need update for this resource? I seem to remember this was a problem for SEPA Instant associations, because customers would lose service between the delete and create.

2020-09-16 14:50 UTC, AMCR commented
checking how to do that

2020-09-17 10:02 UTC, rossmcf approved these changes

2020-09-17 11:49 UTC, merged